### ISSUE TITLE
Not working in IE

### ISSUE THREAD

**Issue by baroso** [awbush/jquery-fastLiveFilter#3]
Your Plugin does not seem to work right in IE!

When I call up ...

http://anthonybush.com/projects/jquery_fast_live_filter/comparison/

... and type something, it shows the time but no results!

**Comment by awbush** [comment]
Which version of IE?

On Dec 6, 2011, at 4:40 AM, baroso
reply@reply.github.com
wrote:

**Comment by baroso** [comment]
It does not work at all on IE6 and IE7 because of the following error (on the page)

$("#fastLiveFilter .filter_input").fastLiveFilter("#fastLiveFilter .list_to_filter", {
    callback: function(total) { fastLiveFilterNumDisplayed.html(total); },
});

IE6 and IE7 dislike the comma after the callback function ...

$("#fastLiveFilter .filter_input").fastLiveFilter("#fastLiveFilter .list_to_filter", {
    callback: function(total) { fastLiveFilterNumDisplayed.html(total); }
});

IE8 ignores this error and seems to filter the list, but does not view the results!

I've not tested it on IE9 ...

**Comment by baroso** [comment]
I found the Problem ... IE doesn't know the "textContent" property of the "li" element!!!

http://stackoverflow.com/questions/1359469/innertext-works-in-ie-but-not-in-firefox

**Comment by baroso** [comment]
Here's a quick fix ...

... this ...

```
        if ((li.textContent || li.innerText || "").toLowerCase().indexOf(filter) >= 0) {
```

... instead of this ...

```
        if ((li.textContent || "").toLowerCase().indexOf(filter) >= 0) {
```

... but this needs to be tested in other Browsers!!!

I tested it and it works in: FF8, IE8, Safari4, Chrome5, Opera11

BEWARE ... you probably should be using the text() method of jQuery ... see the following posts ...

http://stackoverflow.com/questions/6272767/firefoxs-textcontent-doesnt-match-chromes-innertext
http://www.davidtong.me/innerhtml-innertext-textcontent-html-and-text/

**Comment by awbush** [comment]
Thanks, I'll put that in.

I don't really want to use `text()` because it makes it 2-3 times slower.  Accordingly to the posts, it wouldn't be much help for this plug-in anyway (e.g. it's not going to be used to filter `<script>` tags, and differing behavior with regards to newlines won't affect the filtering process in a meaningful way).

That said, it would be possible to use `text()` _and_ have it be fast by caching up all the list item selectors, though memory usage may increase slightly in doing so.  Will save that as a last recourse.
